server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: user-service
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/userservice
    username: postgres
    password: test

jwt:
  header: Authorization
  secret: eB9aQjm3N0HF6Xqbj6N0c7picYrhLBze
  expire: 1209600

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true