server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: mainapp

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  header: Authorization
  secret: eB9aQjm3N0HF6Xqbj6N0c7picYrhLBze
  expire: 1209600

zuul:
  routes:
    user-service:
      path: /user-service/**
      url: http://localhost:8081/
    translation-service:
      path: /translation-service/**
      url: http://localhost:8082/
