server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: mainapp

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true