server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: gateway

eureka:
  dashboard:
    path: /eurekaui
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8080/eureka

zuul:
  prefix: /api
  routes:
    user-service:
      path: /user-service/**
      url: http://localhost:8081/
    translation-service:
      path: /translation-service/**
      url: http://localhost:8082/