server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: translation-service
#  sql:
#    init:
#      mode: always
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    open-in-view: false
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/userservice
#    username: postgres
#    password: test

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true