server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: translation-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

deepL:
  endpoint: https://api-free.deepl.com/v2/translate
  apiKey: 6d831dca-c882-4f8a-d68e-77e51dc8751e:fx

languagetool:
  endpoint: https://api.languagetool.org/v2/check

text-processing:
  endpoint: http://text-processing.com/api/sentiment/